# 服务器 配置
server:
  # 服务器 端口
  port: 80
#
# Spring Boot 配置
spring:
  #
  # 数据库 配置
  datasource:
    # 数据库 驱动名称（包括包名）
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库 URL
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=GMT%2B8
    # 数据库 用户名
    username: root
    # 数据库 密码
    password: root
  #
  # 配置文件 配置
  profiles:
    # 激活 配置
    # dev-sql：MyBatis Plus 中性能及SQL打印等配置
    # security：Security 配置文件
    # weixin-open：微信开放平台 配置文件
    # alipay：支付宝 配置文件
    active: dev-sql,security,weixin-open,alipay
  #
  # Thymeleaf 配置
  thymeleaf:
    # 是否启用模板缓存。
    cache: false
#
# MyBatis Plus 配置
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  # 必须配置（否则出现：org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)）
  mapper-locations: classpath:mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，
  # 而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）。
  type-aliases-package: cn.com.xuxiaowei.security.entity
  # 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性，
  # 具体使用请结合 枚举注入（https://mp.baomidou.com/guide/enum.html） 查看。
  type-enums-package: cn.com.xuxiaowei.security.enums
  global-config:
    db-config:
      # 逻辑已删除值,(逻辑删除下有效，默认值：1)
      logic-delete-value: 1
      # 逻辑未删除值,(逻辑删除下有效，默认值：0)
      logic-not-delete-value: 0
#
# 日志 配置
logging:
  level:
    web: debug
    cn.com.xuxiaowei: debug
