# 微信开放平台 配置
# 资料：
# 网站应用微信登录开发指南：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN
# 授权后接口调用（UnionID）：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316518&token=&lang=zh_CN
weixin:
  open:
    # AppID
    # 请修改此处（微信开放平台：https://open.weixin.qq.com/ --> 网站应用）
    app-id:
    # AppSecret
    # 请修改此处（微信开放平台：https://open.weixin.qq.com/ --> 网站应用）
    app-secret:
    # REDIRECT_URI
    # 请修改此处（微信开放平台：https://open.weixin.qq.com/ 中的 网站应用 --> 开发信息 --> 授权回调域，必须是该域名下的网址）
    redirect-uri:
    # 第三方 网页授权开发 URL（固定）
    authorize-url: https://open.weixin.qq.com/connect/qrconnect